services:
  - type: web
    name: dilemmapl-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
